# Generated by Django 5.1.3 on 2025-03-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeLinkApp', '0003_recipient_recipient_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.CharField(max_length=100)),
                ('client_message', models.TextField(max_length=500)),
                ('filled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
