# Generated by Django 5.1.3 on 2025-03-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeLinkApp', '0004_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_at', models.DateTimeField(auto_now_add=True)),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_organType', models.CharField(choices=[('Kidney', 'Kidney'), ('Heart', 'Heart'), ('Lung', 'Lung'), ('Liver', 'Liver'), ('Pancreas', 'Pancreas'), ('Heart Valve', 'Heart Valve')], default='Kidney', max_length=20)),
                ('donor_contact', models.CharField(max_length=50)),
                ('donor_address', models.CharField(max_length=50)),
            ],
        ),
    ]
